/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ies.torredelrey.vista;

import ies.torredelrey.generador.Generador;
import ies.torredelrey.controlador.ReservasJpaController;
import ies.torredelrey.modelo.Administrador;
import ies.torredelrey.modelo.Reservas;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Daniel Gutierrez Ramirez
 * Clase Menu
 * Permite moverte por los diferentes menus, visitar links y que te salga el Informe . 
 * @version 1.0
 */

public class Menu extends javax.swing.JFrame {

    private Administrador administrador;
    private ReservasJpaController res;

    /**
     * Creates new form Menu
     */
    
    /**
     * Constructor que recibe un objeto Administrador.
     * Inicializa los componentes de la interfaz gráfica y muestra el saludo correspondiente al administrador.
     * 
     * @param administrador El administrador que ha iniciado sesión.
     */
    public Menu(Administrador administrador) {
        this.administrador = administrador;
    }
    private String nombreAdministrador;

    /**
     * Constructor que recibe el nombre del administrador.
     * Inicializa los componentes de la interfaz gráfica y muestra el saludo correspondiente al administrador.
     * 
     * @param nombreAdministrador El nombre del administrador que ha iniciado sesión.
     */
    public Menu(String nombreAdministrador) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/LogoPaxis.jpeg")).getImage()); //icono de pantalla
        setLocationRelativeTo(null); //centrar la pantalla
        setResizable(false); // no se pueda maximizar
        this.nombreAdministrador = nombreAdministrador;
        // Mostrar el saludo del administrador al entrar al Menu
        lblSaludo.setText("Hola " + nombreAdministrador + ", bienvenido");
        // creamos una instancia del controlador UsuariosJpaController
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence");
        res = new ReservasJpaController(emf);
    }
    
    /**
     * Constructor por defecto.
     * Inicializa los componentes de la interfaz gráfica y crea una instancia del controlador de reservas.
     */
    public Menu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/LogoPaxis.jpeg")).getImage()); //icono de pantalla
        setLocationRelativeTo(null); //centrar la pantalla
        setResizable(false); // no se pueda maximizar
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("persistence");

        // creamos una instancia del controlador UsuariosJpaController
        res = new ReservasJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        panMenu = new javax.swing.JPanel();
        panSecundario = new javax.swing.JPanel();
        inmLogo = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblSaludo = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnActividades = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuPaginaWeb = new javax.swing.JMenu();
        mnuSobreNosotros = new javax.swing.JMenu();
        mnuEquipo = new javax.swing.JMenu();
        mnuPrograma = new javax.swing.JMenu();
        mniCurso = new javax.swing.JMenuItem();
        mniAtencionAlUsuario = new javax.swing.JMenuItem();
        mniAtencionFamilia = new javax.swing.JMenuItem();
        mniAtencionUusuarioFamilia = new javax.swing.JMenuItem();
        mnuSedes = new javax.swing.JMenu();
        MnuSevilla = new javax.swing.JMenuItem();
        mnuAljarafe = new javax.swing.JMenuItem();
        mnuAudioVisual = new javax.swing.JMenu();
        mnuContacto = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("jMenu4");

        jMenu9.setText("jMenu9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paxis Inclusion - Menu");

        panMenu.setBackground(new java.awt.Color(255, 204, 204));

        panSecundario.setBackground(new java.awt.Color(255, 255, 255));

        inmLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoPaxisPequeño.jpg"))); // NOI18N
        inmLogo.setText("jLabel1");

        lblMenu.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(255, 0, 0));
        lblMenu.setText("Menu Principal");

        javax.swing.GroupLayout panSecundarioLayout = new javax.swing.GroupLayout(panSecundario);
        panSecundario.setLayout(panSecundarioLayout);
        panSecundarioLayout.setHorizontalGroup(
            panSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSecundarioLayout.createSequentialGroup()
                .addComponent(inmLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(panSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSecundarioLayout.createSequentialGroup()
                        .addComponent(lblSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSecundarioLayout.createSequentialGroup()
                        .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        panSecundarioLayout.setVerticalGroup(
            panSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaludo)
                .addGap(44, 44, 44)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSecundarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inmLogo))
        );

        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(0, 0, 255));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnActividades.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActividades.setForeground(new java.awt.Color(255, 0, 0));
        btnActividades.setText("Actividades");
        btnActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadesActionPerformed(evt);
            }
        });

        btnReservas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReservas.setForeground(new java.awt.Color(0, 204, 0));
        btnReservas.setText("Reservas");
        btnReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasActionPerformed(evt);
            }
        });

        btnInformes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInformes.setForeground(new java.awt.Color(255, 153, 0));
        btnInformes.setText("Informes");
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMenuLayout = new javax.swing.GroupLayout(panMenu);
        panMenu.setLayout(panMenuLayout);
        panMenuLayout.setHorizontalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInformes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panMenuLayout.createSequentialGroup()
                .addComponent(panSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panMenuLayout.setVerticalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addComponent(panSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnUsuarios)
                .addGap(18, 18, 18)
                .addComponent(btnActividades)
                .addGap(18, 18, 18)
                .addComponent(btnReservas)
                .addGap(18, 18, 18)
                .addComponent(btnInformes)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        mnuPaginaWeb.setText("Pagina WEB");
        mnuPaginaWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuPaginaWebMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuPaginaWeb);

        mnuSobreNosotros.setText("Sobre Nosotros");
        mnuSobreNosotros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSobreNosotrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuSobreNosotros);

        mnuEquipo.setText("Equipo");
        mnuEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuEquipoMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuEquipo);

        mnuPrograma.setText("Programas");

        mniCurso.setText("Cursos");
        mniCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCursoActionPerformed(evt);
            }
        });
        mnuPrograma.add(mniCurso);

        mniAtencionAlUsuario.setText("Atencio al Usuario");
        mniAtencionAlUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mniAtencionAlUsuarioMouseClicked(evt);
            }
        });
        mniAtencionAlUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAtencionAlUsuarioActionPerformed(evt);
            }
        });
        mnuPrograma.add(mniAtencionAlUsuario);

        mniAtencionFamilia.setText("Atencion a la Familia");
        mniAtencionFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAtencionFamiliaActionPerformed(evt);
            }
        });
        mnuPrograma.add(mniAtencionFamilia);

        mniAtencionUusuarioFamilia.setText("Atencion al Usuario y Familia");
        mniAtencionUusuarioFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAtencionUusuarioFamiliaActionPerformed(evt);
            }
        });
        mnuPrograma.add(mniAtencionUusuarioFamilia);

        jMenuBar1.add(mnuPrograma);

        mnuSedes.setText("Sedes");

        MnuSevilla.setText("Sevilla");
        MnuSevilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuSevillaActionPerformed(evt);
            }
        });
        mnuSedes.add(MnuSevilla);

        mnuAljarafe.setText("Aljarafe");
        mnuAljarafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAljarafeActionPerformed(evt);
            }
        });
        mnuSedes.add(mnuAljarafe);

        jMenuBar1.add(mnuSedes);

        mnuAudioVisual.setText("AudioVisual");
        mnuAudioVisual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAudioVisualMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuAudioVisual);

        mnuContacto.setText("Contacto");
        mnuContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuContactoMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuContacto);

        mnuSalir.setBackground(new java.awt.Color(255, 0, 0));
        mnuSalir.setForeground(new java.awt.Color(255, 0, 0));
        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Acción que se ejecuta al seleccionar la opción de cursos en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mniCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCursoActionPerformed
                                              
        String url = "https://paxisinclusion.org/cursos"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_mniCursoActionPerformed
/**
 * Acción que se ejecuta al seleccionar la opción de Sevilla en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void MnuSevillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSevillaActionPerformed
        String url = "https://paxisinclusion.org/sevilla"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_MnuSevillaActionPerformed
/**
 * Acción que se ejecuta al seleccionar la opción de Pagina Web en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mnuPaginaWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPaginaWebMouseClicked
        String url = "https://paxisinclusion.org/"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mnuPaginaWebMouseClicked
/**
 * Acción que se ejecuta al seleccionar la opción de sobre nosotros en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mnuSobreNosotrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSobreNosotrosMouseClicked
        String url = "https://paxisinclusion.org/sobre-nosotros"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mnuSobreNosotrosMouseClicked
/**
 * Acción que se ejecuta al seleccionar la opción de equipo en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mnuEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuEquipoMouseClicked
        String url = "https://paxisinclusion.org/equipo"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mnuEquipoMouseClicked
/**
 * Acción que se ejecuta al seleccionar la opción de atencion al usuario en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mniAtencionAlUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniAtencionAlUsuarioMouseClicked
        String url = "https://paxisinclusion.org/atencion-al-usuario"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mniAtencionAlUsuarioMouseClicked
/**
 * Acción que se ejecuta al seleccionar la opción de atencion a la familia en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mniAtencionFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAtencionFamiliaActionPerformed
        String url = "https://paxisinclusion.org/atencion-a-la-familia"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mniAtencionFamiliaActionPerformed
/**
 * Acción que se ejecuta al seleccionar la opción de atencion de usuarios y familias en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mniAtencionUusuarioFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAtencionUusuarioFamiliaActionPerformed
        String url = "https://paxisinclusion.org/atencion-al-usuario-y-la-familia"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mniAtencionUusuarioFamiliaActionPerformed
/**
 * Acción que se ejecuta al seleccionar la opción de aljarafe en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mnuAljarafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAljarafeActionPerformed
        String url = "https://paxisinclusion.org/aljarafe"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mnuAljarafeActionPerformed
/**
 * Acción que se ejecuta al seleccionar la opción de audiovisual en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mnuAudioVisualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAudioVisualMouseClicked
        String url = "https://paxisinclusion.org/descargas"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mnuAudioVisualMouseClicked
/**
 * Acción que se ejecuta al seleccionar la opción de contacto en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mnuContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuContactoMouseClicked
        String url = "https://paxisinclusion.org/contacto"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mnuContactoMouseClicked
 /**
     * Acción ejecutada al presionar el botón de salir.
     * Cierra la ventana actual y abre la ventana de login.
     * 
     * @param evt El evento de acción.
     **/
    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        //vuelta a la pagina principal
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnuSalirMouseClicked
/**
 * Acción que se ejecuta al seleccionar la opción de atencion al usuario en el menú.
 * Abre la URL de la página de cursos en un navegador web predeterminado.
 * 
 * @param evt El evento de acción.
 */
    private void mniAtencionAlUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAtencionAlUsuarioActionPerformed
        String url = "https://paxisinclusion.org/atencion-al-usuario"; // La URL que deseas abrir

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el enlace: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_mniAtencionAlUsuarioActionPerformed
    /**
     * Acción ejecutada al presionar el botón de Usuarios.
     * Cierra la ventana actual y abre la ventana de menu usuarios.
     * 
     * @param evt El evento de acción.
     **/
    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        //ir al menu de usuarios
        MenuUsuarios usuarios = new MenuUsuarios(); 
        usuarios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUsuariosActionPerformed
    /**
     * Acción ejecutada al presionar el botón de actividades.
     * Cierra la ventana actual y abre la ventana de menu actividades.
     * 
     * @param evt El evento de acción.
     **/
    private void btnActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadesActionPerformed
        //ir al menu de actividades
        MenuActividades actividades = new MenuActividades(); 
        actividades.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActividadesActionPerformed
 /**
     * Acción ejecutada al presionar el botón de reservas.
     * Cierra la ventana actual y abre la ventana de registrar menu reservas.
     * 
     * @param evt El evento de acción.
     **/
    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        //ir al menu de reservas
        MenuReserva reserva = new MenuReserva();
        reserva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReservasActionPerformed
 /**
     * Acción ejecutada al presionar el botón de Informes.
     * te muestra en pdp el informe de las reservas por usuario y actividad.
     * 
     * @param evt El evento de acción.
     **/
    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        List<Reservas> reservas = res.findReservasEntities();
        if (reservas != null && !reservas.isEmpty()) {
            Generador.leerInformeReservas(reservas, "src\\main\\resources\\report\\Reservas.jasper", "Reservas.pdf");
        } else {
            System.out.println("No hay reservas para generar el informe.");
        }
        
    }//GEN-LAST:event_btnInformesActionPerformed

    /**
     * Método principal que lanza la aplicación.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuSevilla;
    private javax.swing.JButton btnActividades;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnReservas;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel inmLogo;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JMenuItem mniAtencionAlUsuario;
    private javax.swing.JMenuItem mniAtencionFamilia;
    private javax.swing.JMenuItem mniAtencionUusuarioFamilia;
    private javax.swing.JMenuItem mniCurso;
    private javax.swing.JMenuItem mnuAljarafe;
    private javax.swing.JMenu mnuAudioVisual;
    private javax.swing.JMenu mnuContacto;
    private javax.swing.JMenu mnuEquipo;
    private javax.swing.JMenu mnuPaginaWeb;
    private javax.swing.JMenu mnuPrograma;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenu mnuSedes;
    private javax.swing.JMenu mnuSobreNosotros;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel panSecundario;
    // End of variables declaration//GEN-END:variables
}
