/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ies.torredelrey.vista;

import ies.torredelrey.controlador.AdministradorJpaController;
import ies.torredelrey.modelo.Administrador;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Daniel Gutierrez Ramirez
 * Clase Restablecer Contraseña
 * Permite modificar la contraseña del administrador. . 
 * @version 1.0
 */
public class RestablecerContrasena extends javax.swing.JFrame {
    private EntityManagerFactory emf;
    private AdministradorJpaController admin;
    /**
     * Creates new form RestablecerContraseña
     */
    /**
     * Constructor por defecto
     * Inicializa los componentes y establece configuraciones básicas de la ventana.
     */
    public RestablecerContrasena() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/img/LogoPaxis.jpeg")).getImage()); //icono de pantalla
        setLocationRelativeTo(null); //centrar la pantalla
        setResizable(false); // no se pueda maximizar
        emf = Persistence.createEntityManagerFactory("persistence");
        admin = new AdministradorJpaController(emf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panRestablecer = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblContrasena1 = new javax.swing.JLabel();
        txtContrasena2 = new javax.swing.JTextField();
        lblContrasena2 = new javax.swing.JLabel();
        txtContrasena1 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paxis Inclusion - Restablecer Contraseña");

        panRestablecer.setBackground(new java.awt.Color(255, 204, 204));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoPaxisPequeño.jpg"))); // NOI18N

        lblDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDni.setText("Dni: ");

        txtDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblContrasena1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContrasena1.setText("Repita Contraseña:");

        txtContrasena2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblContrasena2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContrasena2.setText("Nueva Contraseña:");

        txtContrasena1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAceptar.setBackground(new java.awt.Color(51, 255, 51));
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 0, 255));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panRestablecerLayout = new javax.swing.GroupLayout(panRestablecer);
        panRestablecer.setLayout(panRestablecerLayout);
        panRestablecerLayout.setHorizontalGroup(
            panRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRestablecerLayout.createSequentialGroup()
                .addGroup(panRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(imgLogo))
                    .addGroup(panRestablecerLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(panRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                .addComponent(txtContrasena2)
                                .addComponent(txtContrasena1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRestablecerLayout.createSequentialGroup()
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(btnCancelar)
                                .addGap(28, 28, 28)
                                .addComponent(btnReset))
                            .addGroup(panRestablecerLayout.createSequentialGroup()
                                .addGroup(panRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        panRestablecerLayout.setVerticalGroup(
            panRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRestablecerLayout.createSequentialGroup()
                .addComponent(imgLogo)
                .addGap(18, 18, 18)
                .addComponent(lblDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblContrasena2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContrasena1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasena2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(panRestablecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar)
                    .addComponent(btnReset))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRestablecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panRestablecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Método que se ejecuta al presionar el botón "aceptar".
     * Valida que las contraseñas sean iguales y que el administador exista y modifica la contraseña.
     * 
     * @param evt El evento de acción.
     */
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        boolean salir = false;
        //validacion de campos en blancos y para que las contraseñas coincidan
        if(txtDni.getText().isBlank() || txtDni.getText().isEmpty()){
            salir=true;
            JOptionPane.showMessageDialog(this,"Introduce un usuario");
        }
        
        if(txtContrasena1.getText().isBlank() || txtContrasena1.getText().isEmpty()){
            salir=true;
            JOptionPane.showMessageDialog(this,"Introduce una contraseña");
        }
        
        if(!txtContrasena1.getText().equals(txtContrasena2.getText())){
            salir=true;
            JOptionPane.showMessageDialog(this,"Las contraseñas deben ser iguales");
        }
        
        if(salir) return;
        //lista de administradores para buscar el dni, si existe se modifica la contraseña
        ArrayList<Administrador> administrador = new ArrayList<>(admin.findAdministradorEntities());
        for(Administrador a : administrador){
            if(a.getDni().equals(txtDni.getText())){
                a.setContraseña(txtContrasena1.getText());
                try {
                    admin.edit(a); //editamos
                } catch (Exception ex) {
                    Logger.getLogger(RestablecerContrasena.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this,"Contraseña cambiada con éxito");
                Login login = new Login();
                login.setVisible(true);
                this.dispose();
                return;
            }
        }

        JOptionPane.showMessageDialog(this,"Ese usuario no existe");
 
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //cerramos y volvemos a login
        //vuelta a la pagina principal
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
/**
     * Método que se ejecuta al presionar el botón "Reset".
     * Resetea los campos y los pone en blancos.
     * 
     * @param evt El evento de acción.
     */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        //reseteamos campos
        txtDni.setText("");
        txtContrasena1.setText("");
        txtContrasena2.setText(""); 
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * Método principal que lanza la aplicación.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestablecerContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel lblContrasena1;
    private javax.swing.JLabel lblContrasena2;
    private javax.swing.JLabel lblDni;
    private javax.swing.JPanel panRestablecer;
    private javax.swing.JTextField txtContrasena1;
    private javax.swing.JTextField txtContrasena2;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables
}
